"""Generate portable C fixtures from the separate high-precision reference."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "tests" / "large_fixtures.h"


def render() -> bytes:
    data = json.loads((ROOT / "oracle" / "large_reference.json").read_text(encoding="utf-8"))
    metadata = data["metadata"]
    lines = [
        "/* GENERATED by tests/generate_large_fixtures.py; do not edit. */",
        "#ifndef PROBSPAN_LARGE_FIXTURES_H",
        "#define PROBSPAN_LARGE_FIXTURES_H",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        f"#define LARGE_ABS_TOL {metadata['absolute_tolerance']!r}",
        f"#define LARGE_REL_TOL {metadata['relative_tolerance']!r}",
        "typedef struct { double x, cdf; } large_cdf_probe;",
        "typedef struct { int64_t events, complements; double mean, lower, upper; bool ready; large_cdf_probe probes[5]; } large_case;",
        "static const large_case large_cases[] = {",
    ]
    for case in data["cases"]:
        values = [f"INT64_C({case['events']})", f"INT64_C({case['complements']})"]
        values += [repr(float(case[key])) for key in ("mean", "lower", "upper")]
        values.append("true" if case["ready"] else "false")
        probes = [
            "{" + repr(probe["x"]) + ", " + repr(float(probe["cdf"])) + "}"
            for probe in case["cdf_probes"]
        ]
        values.append("{" + ", ".join(probes) + "}")
        lines.append("    {" + ", ".join(values) + "},")
    lines += ["};", "#endif"]
    return ("\n".join(lines) + "\n").encode("ascii")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if OUTPUT.read_bytes() != generated:
            raise SystemExit("Large-count C fixture is stale")
        print("Large-count C fixture is current")
    else:
        OUTPUT.write_bytes(generated)
        print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
