"""Emit Step 3 C fixtures from original, expanded, and corrected reference data."""

import argparse
import json
from pathlib import Path

from generate_fixtures import c_float

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "tests" / "analysis_fixtures.h"
EV = {
    name: "PROBSPAN_" + name.upper()
    for name in ("robust_positive", "robust_negative", "crosses_threshold")
}
COMBINATION = {
    name: "PROBSPAN_" + name.upper()
    for name in ("normal_overlap", "critical", "double_positive_window")
}
RELATION = {
    name: "PROBSPAN_" + name.upper()
    for name in (
        "agreement_positive",
        "agreement_negative",
        "conflict",
        "uncertain",
        "history_unavailable",
    )
}


def number(value: float | str) -> str:
    if isinstance(value, str):
        return {"nan": "NAN", "infinity": "INFINITY"}[value]
    return c_float(value)


def ev_literal(item: dict) -> str:
    return (
        "{"
        + ", ".join(
            [c_float(item[key]) for key in ("ev_center", "ev_min", "ev_max")]
            + [EV[item["ev_state"]]]
        )
        + "}"
    )


def subjective_literal(item: dict | None) -> str:
    if item is None:
        return "{0}"
    geometry = (
        "{"
        + ", ".join(
            [
                c_float(item[key])
                for key in (
                    "break_even_win",
                    "break_even_lose_event",
                    "break_even_lose_as_win_probability",
                )
            ]
            + [COMBINATION[item["odds_combination_status"]]]
        )
        + "}"
    )
    sides = []
    for side in ("win", "lose"):
        value = item[side]["robust_margin_index"]
        sides.append(
            "{"
            + ev_literal(item[side])
            + ", "
            + ("false, 0.0" if value is None else "true, " + c_float(value))
            + "}"
        )
    return "{" + ", ".join([str(item["analysis_version"]), geometry, *sides]) + "}"


def historical_literal(item: dict | None) -> str:
    if item is None:
        return "{0}"
    return (
        "{true, "
        + ", ".join(
            "{"
            + ev_literal(item[side])
            + ", "
            + c_float(item[side]["threshold_posterior_probability"])
            + "}"
            for side in ("win", "lose")
        )
        + "}"
    )


def unwrap(expected: dict | str | None) -> tuple[str, dict | str | None]:
    if isinstance(expected, dict) and "error" in expected:
        if expected["code"] != "odds_range":
            raise ValueError("Unexpected reference failure")
        return "PROBSPAN_ODDS_RANGE", None
    if isinstance(expected, dict) and "value" in expected:
        return "PROBSPAN_OK", expected["value"]
    return "PROBSPAN_OK", expected


def history_row(inputs: dict, expected: dict | None, status: str) -> str:
    fields = [
        f"INT64_C({inputs['wins']})",
        f"INT64_C({inputs['losses']})",
        number(inputs["win_odds"]),
        number(inputs["lose_odds"]),
        status,
        historical_literal(expected),
    ]
    return "    {" + ", ".join(fields) + "},"


def render() -> bytes:
    rows = []
    for name in ("v1_vectors.jsonl", "analysis_vectors.jsonl"):
        rows += [
            json.loads(line)
            for line in (ROOT / "oracle" / name).read_text(encoding="utf-8").splitlines()
        ]
    policy = json.loads((ROOT / "oracle" / "numerical_policy.json").read_text(encoding="ascii"))
    lines = [
        "/* GENERATED by tests/generate_analysis_fixtures.py; do not edit. */",
        "#ifndef PROBSPAN_ANALYSIS_FIXTURES_H",
        "#define PROBSPAN_ANALYSIS_FIXTURES_H",
        "#include <math.h>",
        '#include "probspan/probspan.h"',
        f"#define ANALYSIS_ELEMENTARY_ABS_TOL {c_float(policy['elementary_binary64']['absolute_tolerance'])}",
        f"#define ANALYSIS_ELEMENTARY_REL_TOL {c_float(policy['elementary_binary64']['relative_tolerance'])}",
        f"#define ANALYSIS_BETA_ABS_TOL {c_float(policy['scipy_beta_cdf_ppf']['absolute_tolerance'])}",
        f"#define ANALYSIS_BETA_REL_TOL {c_float(policy['scipy_beta_cdf_ppf']['relative_tolerance'])}",
        "typedef struct { int32_t raw; double event_odds, complement_odds; probspan_status status; probspan_subjective_analysis expected; } subjective_analysis_case;",
        "static const subjective_analysis_case subjective_analysis_cases[] = {",
    ]
    for row in rows:
        if row["group"] not in ("subjective_odds", "subjective_odds_validation"):
            continue
        inputs = row["input"]
        status, expected = unwrap(row["expected"])
        fields = [
            str(inputs["p_h_raw"]),
            number(inputs["win_odds"]),
            number(inputs["lose_odds"]),
            status,
            subjective_literal(expected),
        ]
        lines.append("    {" + ", ".join(fields) + "},")
    lines += [
        "};",
        "typedef struct { int64_t events, complements; double event_odds, complement_odds; probspan_status status; probspan_historical_analysis expected; } historical_analysis_case;",
        "static const historical_analysis_case historical_analysis_cases[] = {",
    ]
    for row in rows:
        if row["group"] not in ("historical_odds", "historical_odds_control_flow"):
            continue
        status, expected = unwrap(row["expected"])
        lines.append(history_row(row["input"], expected, status))
    lines += ["};", "static const historical_analysis_case threshold_analysis_cases[] = {"]
    corrected = json.loads(
        (ROOT / "oracle" / "threshold_reference.json").read_text(encoding="ascii")
    )
    for row in corrected["cases"]:
        inputs = {
            "wins": row["events"],
            "losses": row["complements"],
            "win_odds": row["event_odds"],
            "lose_odds": row["complement_odds"],
        }
        lines.append(history_row(inputs, row["expected"], "PROBSPAN_OK"))
    lines += [
        "};",
        "typedef struct { double minimum, maximum; probspan_ev_state state; } ev_state_case;",
        "static const ev_state_case ev_state_cases[] = {",
    ]
    for row in rows:
        if row["group"] == "ev_state":
            lines.append(
                "    {"
                + ", ".join(
                    [
                        c_float(row["input"]["ev_min"]),
                        c_float(row["input"]["ev_max"]),
                        EV[row["expected"]],
                    ]
                )
                + "},"
            )
    lines += [
        "};",
        "typedef struct { double event_odds, complement_odds; probspan_status status; probspan_odds_combination state; } combination_case;",
        "static const combination_case combination_cases[] = {",
    ]
    for row in rows:
        if row["group"] in ("odds_combination", "odds_combination_validation"):
            status, expected = unwrap(row["expected"])
            fields = [
                number(row["input"]["win_odds"]),
                number(row["input"]["lose_odds"]),
                status,
                COMBINATION[expected] if expected is not None else "PROBSPAN_CRITICAL",
            ]
            lines.append("    {" + ", ".join(fields) + "},")
    lines += [
        "};",
        "typedef struct { probspan_ev_state subjective; bool historical_available; probspan_ev_state historical; probspan_model_relation relation; } relation_case;",
        "static const relation_case relation_cases[] = {",
    ]
    for row in rows:
        if row["group"] == "model_relation":
            item = row["input"]
            fields = [
                EV[item["subjective"]],
                "true" if item["historical"] else "false",
                EV[item["historical"]] if item["historical"] else "PROBSPAN_CROSSES_THRESHOLD",
                RELATION[row["expected"]],
            ]
            lines.append("    {" + ", ".join(fields) + "},")
    lines += ["};", "#endif"]
    return ("\n".join(lines) + "\n").encode("ascii")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    payload = render()
    if args.check:
        if OUTPUT.read_bytes() != payload:
            raise SystemExit("Step 3 C fixture is stale")
        print("Step 3 C fixture is current")
    else:
        OUTPUT.write_bytes(payload)
        print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
