"""Emit C-only bit-exact decimal fixtures from the frozen reference records."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "tests" / "decimal_fixtures.h"


def render() -> bytes:
    rows = [
        json.loads(line)
        for line in (ROOT / "oracle" / "decimal_vectors.jsonl")
        .read_text(encoding="ascii")
        .splitlines()
    ]
    lines = [
        "/* GENERATED by tests/generate_decimal_fixtures.py; do not edit. */",
        "#ifndef PROBSPAN_DECIMAL_FIXTURES_H",
        "#define PROBSPAN_DECIMAL_FIXTURES_H",
        "typedef struct { const char *text; uint64_t bits; probspan_status status; } decimal_case;",
        "static const decimal_case decimal_cases[] = {",
    ]
    for row in rows[1:]:
        expected = row["expected"]
        status = {"ok": "PROBSPAN_OK", "odds_range": "PROBSPAN_ODDS_RANGE"}[expected["status"]]
        text = row["input"]
        # Keep individual source lines readable; every concatenated string is
        # below C11's guaranteed 4095-character literal support threshold.
        assert len(text) <= 4095
        lines.append("    {")
        lines += ['        "' + text[i : i + 80] + '"' for i in range(0, len(text), 80)]
        lines.append(f"        , UINT64_C(0x{expected['bits']}), {status}" + "},")
    lines += ["};", "#endif"]
    return ("\n".join(lines) + "\n").encode("ascii")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    payload = render()
    if args.check:
        if OUTPUT.read_bytes() != payload:
            raise SystemExit("Exact decimal fixture is stale")
        print("Exact decimal fixture is current")
    else:
        OUTPUT.write_bytes(payload)
        print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
