"""Emit C-only provenance fixtures from observed frozen transitions."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def boolean(value):
    return "true" if value else "false"


def generate():
    cases = json.loads((ROOT / "oracle/state_reference.json").read_text())["cases"]
    lines = [
        "/* Generated by tests/generate_state_fixtures.py; do not edit. */",
        "typedef struct {",
        "    const char *name; probspan_provenance previous;",
        "    int32_t previous_raw, current_raw; bool subject_changed, exposed_now;",
        "    probspan_provenance expected;",
        "} provenance_case;",
        "static const provenance_case provenance_cases[] = {",
    ]
    for case in cases:
        old, expected = case["previous"], case["expected"]
        fields = [
            json.dumps(case["case"]),
            "{" + boolean(old["exposed"]) + ", " + boolean(old["compromised"]) + "}",
            str(case["previous_raw"]),
            str(case["current_raw"]),
            boolean(case["subject_changed"]),
            boolean(case["evidence_exposed_now"]),
            "{" + boolean(expected["exposed"]) + ", " + boolean(expected["compromised"]) + "}",
        ]
        lines.append("    {" + ", ".join(fields) + "},")
    lines.append("};")
    return ("\n".join(lines) + "\n").encode()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "tests/state_fixtures.h"
    payload = generate()
    if args.check:
        if target.read_bytes() != payload:
            raise SystemExit("State fixtures are stale")
    else:
        target.write_bytes(payload)
    print("State fixtures verified/generated")


if __name__ == "__main__":
    main()
