/* Generated by tests/generate_state_fixtures.py; do not edit. */
typedef struct {
    const char *name; probspan_provenance previous;
    int32_t previous_raw, current_raw; bool subject_changed, exposed_now;
    probspan_provenance expected;
} provenance_case;
static const provenance_case provenance_cases[] = {
    {"no_history_initial", {false, false}, 60, 60, false, false, {false, false}},
    {"insufficient_initial", {false, false}, 60, 60, false, false, {false, false}},
    {"first_exposure_raw_before", {false, false}, 0, 0, false, false, {false, false}},
    {"first_exposure_raw_after", {false, false}, 0, 1, false, true, {true, false}},
    {"first_exposure_identity_before", {false, false}, 60, 60, false, false, {false, false}},
    {"first_exposure_identity_after", {false, false}, 60, 60, true, true, {true, false}},
    {"exposed_identity_before", {false, false}, 60, 60, false, true, {true, false}},
    {"exposed_identity_after", {true, false}, 60, 60, true, false, {true, true}},
    {"raw_zero_to_one_before", {false, false}, 0, 0, false, true, {true, false}},
    {"raw_zero_to_one_after", {true, false}, 0, 1, false, true, {true, true}},
    {"sticky_exposure_initial", {false, false}, 60, 60, false, true, {true, false}},
    {"sticky_exposure_hidden", {true, false}, 60, 60, false, false, {true, false}},
    {"sticky_exposure_no_history", {true, false}, 60, 60, true, false, {true, true}},
    {"sticky_exposure_insufficient", {true, true}, 60, 60, true, false, {true, true}},
    {"noncompromising_initial", {false, false}, 60, 60, false, true, {true, false}},
    {"noncompromising_odds_only", {true, false}, 60, 60, false, true, {true, false}},
    {"noncompromising_reference_off", {true, false}, 60, 60, false, false, {true, false}},
    {"noncompromising_reference_on", {true, false}, 60, 60, false, true, {true, false}},
    {"sticky_compromise_initial", {false, false}, 60, 60, false, true, {true, false}},
    {"sticky_compromise_changed", {true, false}, 60, 70, false, true, {true, true}},
    {"sticky_compromise_restored", {true, true}, 70, 60, false, true, {true, true}},
    {"initial_hidden", {false, false}, 60, 60, false, false, {false, false}},
    {"first_exposure_unchanged", {false, false}, 60, 60, false, true, {true, false}},
};
